* Library Information
 Readme.org --- helm extensions for delicious bookmarks

-- Filename: helm-delicious.el
-- Description: 
-- Author: Thierry Volpiatto <thierry.volpiatto@gmail.com>
-- Maintainer: Joe Bloggs <vapniks@yahoo.com>
-- Copyright (C) 2008, 2009 Thierry Volpiatto, all rights reserved
-- Version: 1.0
-- Last-Updated: 06/06/2013 03:00:00
-- URL: https://github.com/vapniks/helm-delicious
-- Keywords: 
-- Compatibility: Gnus Emacs 24.3

Features that might be required by this library: `helm' `xml'

* Commentary
Helm interface for Delicious bookmarks.
This code uses curl and wget. You need to install `helm' also.

** Use

M-x helm-delicious
That should create a "~/.delicious-cache" file.
(you can set that to another value with `helm-c-delicious-cache-file')
You can also add `helm-c-source-delicious-tv' to the `helm-sources'.

* Installation

 - Make sure you have a delicious account first: http://delicious.com/
 - Store the username and password, either in your emacs .init file in the variables 
   `helm-delicious-user' and `helm-delicious-password' or in your auth-sources file (usually ~/.authinfo or ~/.netrc,
   see the auth-sources variable) with a line like this: 

    machine api.del.icio.us:443 port https login xxxxx password xxxxx

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this helm-delicious is part of the emacs packages you can install.  
   Just type M-x package-install helm-delicious marmalade 
 - Otherwise download the library from here, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'helm-delicious) in your ~/.emacs file


